### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by smalls12** [tinpotnick/project-mediaswitch#1]
Hey! So whats the status of this project?
Looking for something to play around with. :)

**Comment by tinpotnick** [comment]
Hi Smalls12,

Thanks for your interest. I would love some extra help on this project. It
has stalled at the moment because of other priorities in our business - but
I do want to continue and would happily help out anyone who wanted to
contribute.

KR

Nick

**Comment by smalls12** [comment]
My initial thought was to try and get this running on some raspberry pis I have lying around.
I would cross compile the three components outlined in the README.
I would first probably try and compile everything with cmake.

**Comment by smalls12** [comment]
I'm working through compiling everything via cmake.

This will make cross compiling easier.

I have the common lib and the sip executable done; still working on the rtp executable; I've been raising new issues as I come across them.

Are you open to using cmake if I create a pull request?

**Comment by tinpotnick** [comment]
I have no experience with cmake. What are the advantages?

**Comment by smalls12** [comment]
My experience is that it replaces creating and maintaining Makefiles.
It also lends itself to easy compile for multiple platforms.
You already appear to have a set of working makefiles, that cmake would be replacing.
I would use cmake to then switch out different toolchains seamlessly to build for ubuntu 18.04, or for the raspberry pi.
That could also be extended to build on Windows easily.

**Comment by tinpotnick** [comment]
Cool - go for it.

**Comment by smalls12** [comment]
I've made a pull request if you can check it out.

**Comment by smalls12** [comment]
Going to go ahead and close this now :)
