### ISSUE TITLE
boost 1.70 breaking change

### ISSUE THREAD

**Issue by smalls12** [tinpotnick/project-mediaswitch#2]
When compiling I get the following error

```
/home/src/3rdparty/project-mediaswitch/projectlib/projecthttpserver.cpp:32:49: error: 
‘boost::asio::ip::tcp::acceptor {aka class boost::asio::basic_socket_acceptor<boost::asio::ip::tcp>}’ 
has no member named ‘get_io_service’
     projecthttpconnection::create( httpacceptor.get_io_service() );
```

Looks like `get_io_service()` was deprecated in boost 1.70.

Not sure how difficult a change this is to support.

More info here
https://stackoverflow.com/questions/58453017/boost-asio-tcp-socket-1-70-not-backward-compatible

**Comment by tinpotnick** [comment]
Ah, I haven't looked since late last year - this must be recent

**Comment by smalls12** [comment]
I can always downgrade boost to an earlier version to move on :)

**Comment by smalls12** [comment]
I think I have a fix for this I can create another pull request for.
I don't have a setup to prove the system is working.

**Comment by smalls12** [comment]
Closing.
