### ISSUE TITLE
Where to find ilbc library

### ISSUE THREAD

**Issue by smalls12** [tinpotnick/project-mediaswitch#3]
The README says install `ilbc-devel` but that package does not seem to exist.

Still looking though.

**Comment by smalls12** [comment]
Oh found this in buildroot
`https://freeswitch.org/stash/scm/sd/libilbc.git`

seems like the right lib

**Comment by tinpotnick** [comment]
Which distro are you using? I think fedora is libilbc-dev

**Comment by smalls12** [comment]
They moved there repo to github
https://github.com/signalwire/libilbc

but I get the following error with that lib
```
In file included from /home/src/3rdparty/project-mediaswitch/rtp/projectrtpchannel.h:26:0,
                 from /home/src/3rdparty/project-mediaswitch/rtp/projectrtpchannel.cpp:10:
/home/src/3rdparty/project-mediaswitch/rtp/projectrtpcodecx.h:79:3: error: ‘iLBC_encinst_t’ does not name a type; did you mean ‘ilbc_ulp_inst_t’?
   iLBC_encinst_t *ilbcencoder;
   ^~~~~~~~~~~~~~
   ilbc_ulp_inst_t
/home/src/3rdparty/project-mediaswitch/rtp/projectrtpcodecx.h:80:3: error: ‘iLBC_decinst_t’ does not name a type; did you mean ‘ilbc_ulp_inst_t’?
   iLBC_decinst_t *ilbcdecoder;
   ^~~~~~~~~~~~~~
   ilbc_ulp_inst_t

```

maybe its not the right lib?

**Comment by smalls12** [comment]
I'm on ubuntu 18.04

**Comment by tinpotnick** [comment]
It should be in libilbc-dev?

**Comment by smalls12** [comment]
Found some documentation on how to install via aptitude.
But seems to fail to install for security reasons.

I did find another libilbc repo though.
https://github.com/TimothyGu/libilbc

And this addresses the above error with `iLBC_encint_t` and `iLBC_decinst_t`

**Comment by smalls12** [comment]
Going to go ahead and close this :)
